---
title: "Connecticut"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(dplyr)
library(ggplot2)
library(ghibli)

theme_set(theme_bw())
## Set up the cache and config
  db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-species-swap.sqlite"))
  cache <- storr::storr_dbi("datatable", "keystable", db)
  cache$del(key = "lock", namespace = "session")
  
  loadd(all_overlaps, cache = cache)
loadd(all_smooths, cache = cache)  
loadd(all_svs, cache = cache)
loadd(all_composition, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)

all_overlaps <- filter(all_overlaps, is.na(sim_seed))
all_smooths <- filter(all_smooths, is.na(sim_seed))
all_svs <- filter(all_svs, is.na(sim_seed))
all_composition <- filter(all_composition, is.na(sim_seed))


isd_r2 <- function(focal, compare) {
  
  focal_mean <- mean(focal)

  numer <- sum((focal - compare) ^ 2)
  denom <- sum((focal - focal_mean) ^ 2)
  1 - (numer/denom)
}
```

## Time periods

```{r}

route_years <- select(all_overlaps, route, region, location.bcr, location.routename, startyears, endyears) %>%
  distinct() %>%
  mutate(start = as.integer(substr(startyears, 0, 4)),
         end = as.integer(substr(endyears, 25,28)),
         startend = as.integer(substr(startyears, 25, 28)),
         endbegin = as.integer(substr(endyears, 0, 4))) %>%
  mutate(nyears = end - start) %>%
  mutate(startlate = start > 1975,
         endearly = end < 2010,
         startconsec = startend == start + 4,
         endconsec = endbegin == end - 4) %>%
  group_by_all() %>%
  mutate(weirdtime = startlate | endearly) %>%
  ungroup()



ggplot(route_years, aes(x = start, y = as.factor(route), color = weirdtime)) + 
  geom_errorbar(aes(xmin = start, xmax = end)) + xlab("Time coverage") + ylab("Route")



```


## Overlap in ISD and species composition

```{r}

all_overlaps <- left_join(all_overlaps, all_composition) %>% left_join(select(route_years, route, nyears, weirdtime))

ggplot(all_overlaps, aes(composition_overlap, overlap, color = weirdtime)) + geom_point() + geom_abline(intercept = 0, slope = 1) + xlim(.5, 1) + ylim(0.5,1)


```


## State variables

```{r}

all_sv_wide <- all_svs %>%
  select(timechunk, energy, biomass, abundance,route, region, sim_seed) %>%
  tidyr::pivot_wider(id_cols = c("route", "region", "sim_seed"), names_from = timechunk, values_from = c("energy", "biomass", "abundance"))

all_sv_change <- all_sv_wide %>%
  mutate(energy_lr = log(energy_end / energy_start),
         biomass_lr = log(biomass_end / biomass_start),
         abundance_lr = log(abundance_end/ abundance_start)) %>%
  left_join(select(route_years, route, nyears, weirdtime))


ggplot(all_sv_change, aes(abundance_lr, energy_lr, color= weirdtime)) + geom_point() + geom_abline(intercept = 0, slope = 1) 

```



```{r}

all_long_smooths <- all_smooths %>% left_join(select(route_years, route, weirdtime)) %>% filter(!weirdtime)

ggplot(all_long_smooths, aes(mass, start, group= route)) + geom_line()
```

```{r}

all_long_smooths <- all_long_smooths %>%
  group_by(mass) %>%
  mutate(mean_diff = mean(end - start),
         mean_start = mean(start),
         mean_end = mean(end)) %>%
  ungroup()

ggplot(all_long_smooths, aes(mass, end - start, group = route)) + geom_segment(aes(x = mass, y = 0, xend = mass, yend = end - start), alpha = .05) + xlim(1, 8) + geom_line(aes(mass, mean_diff), color = "green", alpha = .05)

all_long_smooths %>% summarize(diff_r2 = isd_r2(density_diff, mean_diff))


ggplot(all_long_smooths, aes(mass, start, group = route)) + geom_segment(aes(x = mass, y = 0, xend = mass, yend =  start), alpha = .05) + xlim(1, 8) + geom_line(aes(mass, mean_start), color = "green", alpha = .05)

all_long_smooths %>% summarize(start_r2 = isd_r2(start, mean_start))

ggplot(all_long_smooths, aes(mass, end, group = route)) + geom_segment(aes(x = mass, y = 0, xend = mass, yend = end), alpha = .05) + xlim(1, 8) + geom_line(aes(mass, mean_end), color = "green", alpha = .05)

all_long_smooths %>% summarize(end_r2 = isd_r2(end, mean_end))


```


```{r}

meanshift <- select(all_long_smooths, mass, mean_diff) %>%
  distinct()


sum(abs(meanshift$mean_diff)) / 2

filter(all_overlaps, !weirdtime) %>%
  select(route, overlap) %>%
  mutate(change = 1-overlap)

```


