---
title: "Comparisons"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(drake)

theme_set(theme_bw())
## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-neon.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(allComps, cache = cache)

DBI::dbDisconnect(db)
rm(cache)

sites <- read.csv(here::here("neon_mammals", "provisional_rata_use", "provisional_processed_rata.csv")) %>%
  select(siteID, domainID) %>%
  distinct()

allComps <- left_join(allComps, sites, by  = c("site.x" = "siteID")) %>%
  left_join(sites, by = c("site.y" = "siteID")) %>%
  mutate(same_domain = domainID.x == domainID.y)

```

```{r}

allCompsObs <- filter(allComps, sim  < 0)

allCompsNull <- filter(allComps, sim > 0)

allCompsCompare <- allCompsNull %>%
  left_join(
    select(
      rename(
        allCompsObs, obs_isd_overlap = isd_overlap
      ),
      -sim, -shuffle_seed
    )
  )

allCompsPerc <- allCompsCompare %>%
  group_by(
    site.x, site.y
  ) %>%
  mutate(nlower = sum(isd_overlap < obs_isd_overlap),
         nlowerinc = sum(isd_overlap <= obs_isd_overlap), # there are no ties so far
         nsims = length(unique(sim)),
         mean_isd_overlap = mean(isd_overlap),
         sd_isd_overlap = sd(isd_overlap))%>%
  mutate(percentile = nlower / nsims,
         ses = (obs_isd_overlap - mean_isd_overlap) / sd_isd_overlap) %>%
  ungroup() %>%
  select(-isd_overlap, -sim, -shuffle_seed) %>%
  distinct()

ggplot(allCompsPerc, aes(percentile)) +
  geom_histogram() +
  geom_vline(xintercept = c(.95)) 

ggplot(allCompsPerc, aes(ses)) +
  geom_histogram() +
  geom_vline(xintercept = c(-1.96, 1.96)) 

ggplot(allCompsPerc, aes(percentile)) +
  geom_histogram(bins =20) +
  geom_vline(xintercept = c(.95)) +
  facet_wrap(vars(haver < 1000*1000), scales = "free_y")


ggplot(allCompsPerc, aes(haver, percentile, color = same_domain)) +
  geom_point() +
  geom_vline(xintercept = 1000* 1000)
```


```{r}

allCompsConserved <- filter(allCompsPerc, percentile > .95)

```


```{r, fig.dim  = c(10,10)}

bySite <- list()
sites <- unique(c(allComps$site.x, allComps$site.y))

for(i in 1:length(sites)) {
  
  site = sites[i]
  this_site_involved <- filter(allCompsPerc, site.x == site | site.y == site )
  
  this_site_info <- data.frame(
    site = site,
    ncomps = nrow(this_site_involved),
    prop_high_perc = mean(this_site_involved$percentile > .95),
    prop_high_ses = mean(this_site_involved$ses > 1.96)
    
  ) 
  
  bySite[[i]] <- this_site_info
  
  
}


bysites <- bind_rows(bySite)


ggplot(filter(allCompsPerc)) +
  geom_segment(aes(y = decimalLatitude.x, x =decimalLongitude.x, yend = decimalLatitude.y, xend = decimalLongitude.y, color = percentile >.95)) +  geom_label(aes(y = decimalLatitude.x, x = decimalLongitude.x, label = site.x)) + geom_label(aes(y = decimalLatitude.y, x=decimalLongitude.y, label = site.y))

site.md <- read.csv(here::here("neon_mammals", "NEON_Field_Site_Metadata_20210226_0.csv"))


bysites <- left_join(bysites, site.md, by = c("site" = "field_site_id"))

filter(bysites, prop_high_ses > .15)
filter(bysites, prop_high_ses < .15)

```
