---
title: "Actual results"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
      toc: true
      df_print: kable

---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
theme_set(theme_bw())


## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(all_results, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)

max10 <- read.csv(here::here("working_routes_max10.csv"))

all_results <- all_results %>%
  mutate(matssname = paste0("bbs_rtrg_", route, "_", statenum)) %>%
  filter(matssname %in% max10$matssname)


onetoone <- geom_abline(slope = 1, intercept = 0)
```

# State variable change

```{r}
# 
# ggplot(all_results, aes(fitted_ratio_caps_abundance, r2_caps_abundance, color = p_caps_abundance > .05, size = r2_caps_abundance)) + geom_point(alpha = .3)

ggplot(all_results, aes(fitted_ratio_caps_abundance)) + geom_histogram() + geom_vline(xintercept = 1)



ggplot(all_results, aes((fitted_ratio_ts_abundance))) + geom_histogram() + geom_vline(xintercept = 1)


ggplot(all_results, aes(fitted_ratio_caps_abundance)) + geom_histogram() + geom_vline(xintercept = 1) + facet_wrap(vars(p_caps_abundance < .05))

all_results %>% 
  mutate(abundance_sig = p_caps_abundance < .05,
         abundance_inc = fitted_ratio_caps_abundance > 1) %>%
  group_by(abundance_sig, abundance_inc) %>%
  summarize(nroutes = dplyr::n()) %>%
  ungroup()


all_results %>% 
  mutate(abundance_sig = p_ts_abundance < .05,
         abundance_inc = fitted_ratio_ts_abundance > 1) %>%
  group_by(abundance_sig, abundance_inc) %>%
  summarize(nroutes = dplyr::n()) %>%
  ungroup()

all_results %>% 
  mutate(energy_sig = p_caps_energy < .05,
         energy_inc = fitted_ratio_caps_energy > 1) %>%
  group_by(energy_sig, energy_inc) %>%
  summarize(nroutes = dplyr::n()) %>%
  ungroup()

all_results %>% 
  mutate(biomass_sig = p_caps_biomass < .05,
         biomass_inc = fitted_ratio_caps_biomass > 1) %>%
  group_by(biomass_sig, biomass_inc) %>%
  summarize(nroutes = dplyr::n()) %>%
  ungroup()


ggplot(all_results, aes(fitted_ratio_caps_abundance, fitted_ratio_caps_biomass, color = p_caps_abundance < .05, shape = p_caps_biomass < .05)) + geom_point() + geom_abline(intercept = 0, slope = 1) + scale_x_log10() + scale_y_log10() + geom_hline(yintercept = 1) + geom_vline(xintercept = 1) + scale_color_viridis_d(option = 'mako', end = .7)


ggplot(all_results, aes(fitted_ratio_caps_abundance, fitted_ratio_caps_energy, color = p_caps_abundance < .05, shape = p_caps_energy < .05)) + geom_point() + geom_abline(intercept = 0, slope = 1) + scale_x_log10() + scale_y_log10() + geom_hline(yintercept = 1) + geom_vline(xintercept = 1) + scale_color_viridis_d(option = 'mako', end = .7)

ggplot(all_results, aes(fitted_ratio_caps_energy - fitted_ratio_caps_abundance)) + geom_histogram() 

summary(all_results$fitted_ratio_caps_energy - all_results$fitted_ratio_caps_abundance)

all_results %>% 
  mutate(mean_energy_sig = p_caps_mean_energy < .05,
         mean_energy_inc = fitted_ratio_caps_mean_energy > 1) %>%
  group_by(mean_energy_sig, mean_energy_inc) %>%
  summarize(nroutes = dplyr::n()) %>%
  ungroup()


summary(lm(fitted_ratio_caps_energy ~ fitted_ratio_caps_abundance, data = all_results))


ggplot(all_results,aes(fitted_ratio_caps_biomass - fitted_ratio_caps_abundance, fitted_ratio_caps_energy - fitted_ratio_caps_abundance)) + geom_point() + geom_line(aes(y = fitted_ratio_caps_biomass - fitted_ratio_caps_abundance))

```


```{r}

ggplot(all_results, aes(isd_turnover)) + geom_histogram()

ggplot(all_results, aes(sp_turnover)) + geom_histogram()

ggplot(all_results, aes(sp_turnover, isd_turnover)) + geom_point() + onetoone

```
