---
title: "5 sites"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(dplyr)
library(ggplot2)
library(ghibli)

theme_set(theme_bw())
## Set up the cache and config
  db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache.sqlite"))
  cache <- storr::storr_dbi("datatable", "keystable", db)
  cache$del(key = "lock", namespace = "session")
  
  loadd(all_overlaps, cache = cache)
loadd(all_smooths, cache = cache)  
loadd(all_svs, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)

```

## Overlaps

```{r}

ggplot(all_overlaps, aes(overlap)) + geom_histogram(bins = 100) 

ggplot(all_overlaps, aes(overlap)) + geom_histogram() + facet_wrap(vars(location.bcr), scales = "free_y")

ggplot(all_overlaps, aes(as.factor(location.bcr), overlap)) + geom_boxplot() + geom_jitter(alpha = .1, size = .5, height = 0)

all_overlaps %>%
  summarize(mean_overlap = mean(overlap),
            sd_overlap = sd(overlap))


all_overlaps %>%
  group_by(location.bcr) %>%
  summarize(mean_overlap = mean(overlap),
            sd_overlap = sd(overlap))
```


Overlap is in general very high, and I don't see this varying in a really pronounced way across BCRs. For comparison, the overlap between Portal 1980-85 and 2010-2014 is .51 (calculated hackily just now so possibly slightly wrong, but ballpark)

That is, like 80% of the ISD is remaining the same across the start and end of the TS. 


## Smooths 

```{r}

smooth_summary <- all_smooths %>% 
  group_by(mass) %>%
  mutate(overall_mean = mean(density_diff)) %>%
  ungroup() %>%
  group_by(location.bcr, mass) %>%
  mutate(bcr_mean = mean(density_diff)) %>%
  ungroup() %>%
  group_by(location.bcr) %>%
  mutate(nroutes = length(unique(route))) %>%
  ungroup()

rg14 <- filter(smooth_summary, location.bcr == 14)

ggplot(rg14, aes(mass, density_diff, group = location.routename, color = density_diff > 0)) + geom_col(position = "stack") + geom_line(aes(mass, bcr_mean * length(unique(rg14$`location.routename`))), color = "black")+ geom_line(aes(mass, overall_mean * length(unique(rg14$`location.routename`))), color = "black", linetype= 3)

bcrs <- unique(smooth_summary$location.bcr)

ggplot(filter(smooth_summary, location.bcr %in% sample(bcrs, size = 4)), aes(mass, density_diff, group = location.routename, color = density_diff >0)) + geom_col(position = "stack") + geom_line(aes(y = bcr_mean * nroutes), color = "black") + theme(legend.position = "none") + scale_color_viridis_d(option = "turbo", begin = .1, end = .9, direction = -1) + facet_wrap(vars(location.bcr), scales = "free_y")

```
