---
title: "Actual results"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
      toc: true
      df_print: kable

---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
theme_set(theme_bw())


## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(all_results, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)

max10 <- read.csv(here::here("working_routes_max10.csv"))

all_results <- all_results %>%
  mutate(matssname = paste0("bbs_rtrg_", route, "_", statenum)) #%>%
#  filter(matssname %in% max10$matssname)


onetoone <- geom_abline(slope = 1, intercept = 0)
```

This whole approach bugs me because of the sheer number of comparisons being made and the .05 threshold. So, don't overinterpret in any single instance.


```{r}


all_results_adj <- all_results %>%
  select(overall_p, `Pr(>|t|)_timeperiodend:currencybiomass`, `Pr(>|t|)_timeperiodend:currencyenergy`, `Pr(>|t|)_timeperiodend`, matssname) %>%
  rename(time_biomass = `Pr(>|t|)_timeperiodend:currencybiomass`,
         time_energy = `Pr(>|t|)_timeperiodend:currencyenergy`,
         time = `Pr(>|t|)_timeperiodend`) %>%
  tidyr::pivot_longer(-matssname, names_to = "comparison", values_to = "p") %>%
  mutate(padj = p.adjust(p, "fdr")) %>%
  tidyr::pivot_wider(id_cols = matssname, names_from = comparison, values_from = c(p, padj))


mean(all_results_adj$padj_overall_p < .05)

all_results_adj_sig <- filter(all_results_adj, padj_overall_p < .05)

sum(all_results_adj_sig$padj_time < .05)
sum(all_results_adj_sig$padj_time_biomass < .05)
sum(((all_results_adj_sig$padj_time_biomass < .05) & !((all_results_adj_sig$padj_time < .05))))
sum(((all_results_adj_sig$padj_time_energy < .05) & !((all_results_adj_sig$padj_time < .05))))
sum(all_results_adj_sig$padj_time_energy < .05)

```

```{r}

all_results <- left_join(all_results, all_results_adj)

ggplot(all_results, aes(abundance_raw_ratio, energy_raw_ratio, shape = (padj_time_energy < .05 & padj_overall_p < .05), color =  (padj_overall_p < .05 & padj_time < .05))) + geom_point() + onetoone + scale_x_log10() + scale_y_log10() + scale_shape(solid = F) + theme(legend.position = "bottom") +
  geom_point(data = filter(all_results, padj_overall_p < .05, padj_time_energy < .05), shape = 17)


ggplot(all_results, aes(abundance_raw_ratio, biomass_raw_ratio, shape = (padj_time_biomass < .05 & padj_overall_p < .05), color =  (padj_overall_p < .05 & padj_time < .05))) + geom_point() + onetoone + scale_x_log10() + scale_y_log10() + scale_shape(solid = F) + theme(legend.position = "bottom") +
  geom_point(data = filter(all_results, padj_overall_p < .05, padj_time_biomass < .05), shape = 17)

ggplot(filter(all_results, padj_overall_p < .05), aes(abundance_raw_ratio)) + geom_histogram()

filter(all_results, padj_overall_p < .05, padj_time < .05) %>%
  group_by(abundance_raw_ratio > 1) %>%
  summarize(prop = dplyr::n())

```

