---
title: "all one"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
theme_set(theme_bw())


## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual-caps.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(all_results, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)
```

```{r}

scld <- all_results %>%
  select(statenum, route, timeperiod, abundance, energy, biomass) %>%
  mutate(matssname = paste0("rtrg_", statenum, "_", route)) %>%
  select(-statenum, -route) %>%
  group_by(matssname) %>%
  mutate(abundance = scale(sqrt(abundance)),
         energy = scale(sqrt(energy)),
         biomass = scale(sqrt(biomass))) %>%
  ungroup()

scld_long <- scld %>%
  tidyr::pivot_longer(-c(timeperiod, matssname), names_to = "currency", values_to = "value")

scld_long_sub <- scld_long %>%
  filter(matssname %in% unique(scld_long$matssname)[1:100])

try <- lm(value ~ timeperiod * currency * matssname, data = scld_long_sub)

library(emmeans)

emm_try <- emmeans(try, specs = ~ (timeperiod) | (currency + matssname))

pairs_try <- as.data.frame(pairs(emm_try))

ggplot(pairs_try, aes(p.value < .05)) + geom_bar() + facet_wrap(vars(currency))

library(brms)


try <- brm(value ~ timeperiod * currency * matssname, data = scld_long_sub)


emm_try <- emmeans(try, specs = ~ (timeperiod) | (currency + matssname))

pairs_try <- as.data.frame(pairs(emm_try))

ggplot(pairs_try, aes(lower.HPD * upper.HPD > 0)) + geom_bar() + facet_wrap(vars(currency))
```
