---
title: "Continental null model"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BBSsize)
library(rwar)
library(ggplot2)
library(dplyr)

route_intersections <- read.csv(here::here("route_species_lists.csv"))

startyears <- 1988:1992
endyears <- 2014:2018
isd_seed = 1977

```


```{r}

g <- granby

orig_g_species <- g$metadata$species_table$id
all_species <- BBSsize::sd_table$id


set.seed(1994)
new_g_species <- sample(all_species, size = length(orig_g_species), replace = F)

g_shuffled <- g

colnames(g_shuffled$abundance) <- new_g_species
```




# Run analyses

```{r}
library(BBSsize)

g_analyses <- all_core_analyses(g, startyears, endyears, isd_seed)

g_shuffled_analyses <- all_core_analyses(g_shuffled, startyears, endyears, isd_seed)

two <- bind_rows(g_analyses, g_shuffled_analyses)


```

## step by step

```{r, eval = T}

ts_isd_actual <- BBSsize::simulate_isd_ts(g, isd_seed = isd_seed)
ts_svs_actual <- get_annual_svs(ts_isd_actual$isd)
ts_lms_actual <- fit_all_timeseries_lms(ts_svs_actual)
caps_svs_actual <- pull_caps(ts_svs_actual, startyears, endyears)
caps_lms_actual <- fit_all_caps_lms(caps_svs_actual)
i_lms_actual <- interaction_lms(caps_svs_actual)
raw_ratios_actual <-  compute_raw_sv_change(caps_svs_actual)
set.seed(isd_seed)
isd_turn_actual <- compare_isds(ts_isd_actual$isd, startyears, endyears)
comp_turn_actual <- compare_species_composition(g, startyears, endyears)

ts_isd_shuffled <- BBSsize::simulate_isd_ts(g_shuffled, isd_seed = isd_seed)
ts_svs_shuffled <- get_annual_svs(ts_isd_shuffled$isd)
ts_lms_shuffled <- fit_all_timeseries_lms(ts_svs_shuffled)
caps_svs_shuffled <- pull_caps(ts_svs_shuffled, startyears, endyears)
caps_lms_shuffled <- fit_all_caps_lms(caps_svs_shuffled)
i_lms_shuffled <- interaction_lms(caps_svs_shuffled)
raw_ratios_shuffled <-  compute_raw_sv_change(caps_svs_shuffled)
set.seed(1994)
isd_turn_shuffled <- compare_isds(ts_isd_shuffled$isd, startyears, endyears)
comp_turn_shuffled <- compare_species_composition(g_shuffled, startyears, endyears)


isds <- bind_rows(list(actual = ts_isd_actual$isd, shuffled =ts_isd_shuffled$isd), .id = "source")

ggplot(isds, aes(log(mass), fill = year > 2000)) + geom_density(alpha = .5) + facet_wrap(vars(source))

```
# Repeatedly for a null model

```{r}

continental_null_model <- function(ts_dat, null_mod_seed = NULL, begin_years = NULL, end_years = NULL, isd_seed = NULL) {
  
  
  if(is.null(null_mod_seed)) {
    set.seed(NULL)
    null_mod_seed <- sample.int(1000000000, 1)
  }
  
  
  ts_locationdat <- ts_dat$metadata$location
  
  ts_richness <- ncol(ts_dat$abundance)
  
  all_species <- BBSsize::sd_table$id


  set.seed(null_mod_seed)
  
  new_ts_species <- sample(all_species, size = ts_richness, replace = F)
  
  shuffled_dat <- ts_dat
  
  colnames(shuffled_dat$abundance) <- new_ts_species
  
  results <- all_core_analyses(shuffled_dat, begin_years, end_years, isd_seed)
  
  results <- results %>%
    dplyr::mutate(
      null_mod_type = "continental",
      null_mod_seed = null_mod_seed
    )
  
  
  results 
}
```


```{r}


r3 <- replicate(50, continental_null_model(g, NULL, startyears, endyears, isd_seed), simplify = FALSE)

nulls <- bind_rows(r3)

```

Always want to check that:

- Results for total abundance and species turnover remain the same
- Multiple, different null_mod_seeds in multiple runs

```{r}

head(nulls$bcd)
head(nulls$null_mod_seed)

```

```{r}

ggplot(nulls, aes(isd_turnover)) + geom_histogram() + geom_vline(xintercept = g_analyses$isd_turnover)

```
