---
title: "Checking local nm at scale"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
library(dplyr)
library(ggplot2)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-localn.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(all_results, cache = cache)


DBI::dbDisconnect(db)
rm(cache)
rm(db)

db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

all_results_actual <- readd(all_results, cache = cache)


DBI::dbDisconnect(db)
rm(cache)
rm(db)

all_results_actual <- all_results_actual %>%
  filter(routename %in% all_results$routename)

```

# Checking


Make sure you have unique seeds - depending on how the Rsession is working it might get kept. (I think I put a stop to that but double check).

```{r}
length(unique(all_results$null_mod_seed))
length(unique(all_results$isd_seed))

```

# Combining

```{r}


all_results <- bind_rows(mutate(all_results_actual, null_mod_type = "actual"), all_results)


ggplot(all_results, aes(isd_turnover, color = null_mod_type)) + geom_histogram() + facet_wrap(vars(routename))


ggplot(all_results, aes(sp_turnover, color = null_mod_type)) + geom_histogram() + facet_wrap(vars(routename))
```

I am not sure about using the null model to look at **trends** because the null model is going to be **starting** from different places. 
