---
title: "all one"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
theme_set(theme_bw())


## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual-caps.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

loadd(all_results, cache = cache)

DBI::dbDisconnect(db)
rm(cache)
rm(db)
```

```{r}

ar <- all_results %>%
  mutate(matssname = paste0("rtrg_", route, "_", statenum))

# 
# lms <- list()
# 
# p.vals <- list()
# 
# for(i in 1:length(unique(ar$matssname))) {
# 
#   thisdat <- filter(ar, matssname == unique(ar$matssname)[i])
# 
#   lms[[i]] <- lm(data = thisdat, mean_biomass ~ timeperiod)
# 
#   thisres <- summary(lms[[i]])
#   p.vals[[i]] <- pf(thisres$fstatistic[1], thisres$fstatistic[2], thisres$fstatistic[3], lower.tail = F)
# 
# }
# 
# ps <- unlist(p.vals)


library(lme4)

wholelme <- lmer(mean_biomass ~ timeperiod + (timeperiod | matssname) , data = ar)
wholelme2 <- lmer(mean_biomass ~ (timeperiod | matssname) , data = ar)
 anova(wholelme, wholelme2)
summary(wholelme)

#summary(lm(mean_biomass ~ timeperiod * matssname, data = ar))

ggplot(ar, aes(year, mean_biomass)) + geom_point()

wholelmefitted <- ar %>% mutate(lmefit = predict(wholelme),
                                lmefitnorand = predict(wholelme, re.form = NA))

ggplot(wholelmefitted, aes(timeperiod, lmefit, group = matssname)) + geom_line(alpha = .1)  + geom_line(aes(y = lmefitnorand), alpha = 1, color = "red")

rsq::rsq(wholelme)
```


There's a weak but ~significant increase in mean body size across the whole dataset. 



```{r e}

wholelme <- lmer(mean_energy ~ timeperiod + (timeperiod | matssname) , data = ar)
wholelme2 <- lmer(mean_energy ~ (timeperiod | matssname) , data = ar)
 anova(wholelme, wholelme2)
summary(wholelme)

#summary(lm(mean_energy ~ timeperiod * matssname, data = ar))

ggplot(ar, aes(year, mean_energy)) + geom_point()

wholelmefitted <- ar %>% mutate(lmefit = predict(wholelme),
                                lmefitnorand = predict(wholelme, re.form = NA))

ggplot(wholelmefitted, aes(timeperiod, lmefit, group = matssname)) + geom_line(alpha = .1)  + geom_line(aes(y = lmefitnorand), alpha = 1, color = "red")

rsq::rsq(wholelme)


```


And by weak I mean 
1. Microscopic
2. Explains ....4% of variation




```{r n}

wholelme <- lmer(scale(sqrt(abundance)) ~ timeperiod + (timeperiod | matssname) , data = ar)
wholelme2 <- lmer(scale(sqrt(abundance))  ~ (timeperiod | matssname) , data = ar)
 anova(wholelme, wholelme2)
summary(wholelme)

#summary(lm(mean_energy ~ timeperiod * matssname, data = ar))

ggplot(ar, aes(year, scale(sqrt(abundance)) )) + geom_point()

wholelmefitted <- ar %>% mutate(lmefit = predict(wholelme),
                                lmefitnorand = predict(wholelme, re.form = NA))

ggplot(wholelmefitted, aes(timeperiod, lmefit, group = matssname)) + geom_line(alpha = .1)  + geom_line(aes(y = lmefitnorand), alpha = 1, color = "red")

rsq::rsq(wholelme)

```
