---
title: "ReSims analysis"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
library(multipanelfigure)
theme_set(theme_bw())
## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("old_caches", "drake-cache-actual-resim.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

#cached(cache = cache)

loadd(all_estimates, cache = cache)

```



Estimated change due to abundance:

`estimated_sim_change_ratio` mean, upper, and lower.


```{r}

ggplot(all_estimates[100:140,], aes(estimated_sim_change_ratio_median, estimated_actual_change_ratio_median, color = matssname)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)+
  geom_abline(intercept = 0, slope = 1) +
## geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper, y = estimated_actual_change_ratio_median), height = .005) +
  #geom_errorbar(aes(ymin = estimated_actual_change_ratio_lower, ymax = estimated_actual_change_ratio_upper, x = estimated_sim_change_ratio_median), width = .005) +
  #scale_color_viridis_d(option='mako', begin = .2, end =.8) +
  #theme(legend.position = "none") +
  facet_wrap(vars(currency)) +
xlim(-1, 2) +
ylim(-2, 3) +
  geom_point(data = filter(all_estimates, matssname =="bbs_rtrg_19_7"), size = 3)

```
## biomass

```{r, fig.dim = c(4,9)}

biomass <- filter(all_estimates, currency == "biomass")

biomass_summary <- biomass %>%
  arrange(estimated_sim_change_ratio_median) %>%
  mutate(sim_change_ratio_rank = row_number()) %>%
  mutate(omatssname = ordered(1:nrow(biomass), labels = matssname))



ggplot(filter(biomass_summary, matssname != "bbs_rtrg_14_33"), aes(estimated_sim_change_ratio_median, omatssname)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper), alpha = .3) + 
 # geom_point(aes(x = estimated_actual_change_ratio_mean), color = "blue", alpha = .6) +
# geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), color = "blue", alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw() +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank()) 

```

```{r}

#loadd(all_sims, cache = cache)

#ggplot(all_sims, aes(year, total_biomass, color = source)) + geom_point() + facet_wrap(vars(matssname,source), scales = "free_y")

```


Some interpretation points...

```{r}

biomass_interp <- biomass_summary %>%
  group_by_all() %>%
  mutate(
    abundance_change_ratio_over_zero = (estimated_sim_change_ratio_upper * estimated_sim_change_ratio_lower) < 0,
    currency_over_abundance = ((estimated_sim_change_ratio_upper < estimated_actual_change_ratio_lower)),
    abundance_over_currency = estimated_sim_change_ratio_lower > estimated_actual_change_ratio_upper,
    currency_decouple = currency_over_abundance | abundance_over_currency
  ) %>%
  ungroup()



ggplot(biomass_interp, aes(estimated_sim_change_ratio_median, omatssname, color = currency_decouple)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper)) + 
 # geom_point(aes(x = estimated_actual_change_ratio_median), color = "blue", alpha = .6) +
  geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw() +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank(), legend.position = "none")


ggplot(biomass_interp, aes(estimated_sim_change_ratio_median, estimated_actual_change_ratio_median, color= currency_decouple)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)+
  geom_abline(intercept = 0, slope = 1) +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper, y = estimated_actual_change_ratio_median), height = .005) +
  geom_errorbar(aes(ymin = estimated_actual_change_ratio_lower, ymax = estimated_actual_change_ratio_upper, x = estimated_sim_change_ratio_median), width = .005) +
  scale_color_viridis_d(option='mako', begin = .2, end =.8) +
  theme_bw() +
  theme(legend.position = "bottom")


mean(biomass_interp$abundance_change_ratio_over_zero)
mean(biomass_interp$estimated_sim_change_ratio_lower > 0)
mean(biomass_interp$estimated_sim_change_ratio_upper < 0)

mean(biomass_interp$abundance_over_currency)
mean(biomass_interp$currency_over_abundance)
mean(biomass_interp$currency_decouple)




```
# energy

```{r, fig.dim = c(4,9)}

energy <- filter(all_estimates, currency == "energy")

energy_summary <- energy %>%
  arrange(estimated_sim_change_ratio_median) %>%
  mutate(sim_change_ratio_rank = row_number()) %>%
  mutate(omatssname = ordered(1:nrow(energy), labels = matssname))



ggplot(energy_summary, aes(estimated_sim_change_ratio_median, omatssname)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper), alpha = .3) + 
 # geom_point(aes(x = estimated_actual_change_ratio_mean), color = "blue", alpha = .6) +
# geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), color = "blue", alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw() +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank()) 

```

```{r}

#loadd(all_sims, cache = cache)

#ggplot(all_sims, aes(year, total_energy, color = source)) + geom_point() + facet_wrap(vars(matssname,source), scales = "free_y")

```


Some interpretation points...

```{r}

energy_interp <- energy_summary %>%
  group_by_all() %>%
  mutate(
    abundance_change_ratio_over_zero = (estimated_sim_change_ratio_upper * estimated_sim_change_ratio_lower) < 0,
    currency_over_abundance = ((estimated_sim_change_ratio_upper < estimated_actual_change_ratio_lower)),
    abundance_over_currency = estimated_sim_change_ratio_lower > estimated_actual_change_ratio_upper,
    currency_decouple = currency_over_abundance | abundance_over_currency
  ) %>%
  ungroup()



ggplot(energy_interp, aes(estimated_sim_change_ratio_mean, omatssname, color = currency_decouple)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper)) + 
 # geom_point(aes(x = estimated_actual_change_ratio_mean), color = "blue", alpha = .6) +
  geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw() +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank(), legend.position = "none")


ggplot(energy_interp, aes(estimated_sim_change_ratio_median, estimated_actual_change_ratio_median, color= currency_decouple)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)+
  geom_abline(intercept = 0, slope = 1) +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper, y = estimated_actual_change_ratio_median), height = .005) +
  geom_errorbar(aes(ymin = estimated_actual_change_ratio_lower, ymax = estimated_actual_change_ratio_upper, x = estimated_sim_change_ratio_median), width = .005) +
  scale_color_viridis_d(option='mako', begin = .2, end =.8) +
  theme_bw() +
  theme(legend.position = "bottom")


mean(energy_interp$abundance_change_ratio_over_zero)
mean(energy_interp$estimated_sim_change_ratio_lower > 0)
mean(energy_interp$estimated_sim_change_ratio_upper < 0)

mean(energy_interp$abundance_over_currency)
mean(energy_interp$currency_over_abundance)
mean(energy_interp$currency_decouple)




```

bbs_rtrg_14_33 is super weird - really huge estimates and error bars.

bbs_rtrg_23_64 has a change estimate of -1.4 which shouldn't be possible. The median does not have this problem. 


<!-- ```{r} -->

<!-- loadd(sims_sgmms_bbs_rtrg_23_64, cache = cache) -->
<!-- loadd(ests_fits_sims_sgmms_bbs_rtrg_23_64, cache = cache) -->
<!-- ggplot(sims_sgmms_bbs_rtrg_23_64, aes(year, total_energy, color = source)) + geom_point() + facet_wrap(vars(source)) -->
<!-- ggplot(ests_fits_sims_sgmms_bbs_rtrg_23_64, aes(estimated_actual_begin)) + geom_density() + facet_wrap(vars(currency)) + geom_density(aes(estimated_actual_end)) -->

<!-- ggplot(ests_fits_sims_sgmms_bbs_rtrg_23_64, aes(estimated_actual_change_ratio)) + geom_density() + facet_wrap(vars(currency)) + xlim(-5, 5) -->


<!-- loadd(sims_sgmms_bbs_rtrg_14_33, cache = cache) -->
<!-- ggplot(sims_sgmms_bbs_rtrg_14_33, aes(year, total_energy, color = source)) + geom_point() + facet_wrap(vars(source)) -->

<!-- ``` -->
