---
title: "Exploring on some examples"
output: 
  github_document:
     toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = F, fig.dim = c(4, 8))
library(dplyr)
library(ggplot2)
library(multipanelfigure)
library(tidybayes)
theme_set(theme_bw())

load(here::here("aspirational_structure", "dev_vignettes", "hbrm_post1.Rds"))


```


```{r}


intercept_cols <- which(grepl(",Intercept]", colnames(hbrm_post1)))

intercept_draws <- hbrm_post1[,intercept_cols] %>%
  mutate(rown = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rown, names_to = "site", values_to = "intercept")

ggplot(filter(intercept_draws, site %in% unique(intercept_draws$site)[1:5]), aes(intercept)) + geom_density() + facet_wrap(vars(site), ncol = 1)



sim_int_cols <- which(grepl(",sourcesim]", colnames(hbrm_post1)))

sim_int_draws <- hbrm_post1[,sim_int_cols] %>%
  mutate(rown = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rown, names_to = "site", values_to = "sim_int")

ggplot(filter(sim_int_draws, site %in% unique(sim_int_draws$site)[1:5]), aes(sim_int)) + geom_density() + facet_wrap(vars(site), ncol = 1)


slope_cols <- which(grepl("timeperiodend]", colnames(hbrm_post1)))

slope_draws <- hbrm_post1[,slope_cols] %>%
  mutate(rown = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rown, names_to = "site", values_to = "slope")

ggplot(filter(slope_draws, site %in% unique(slope_draws$site)[1:5]), aes(slope)) + geom_density() + facet_wrap(vars(site), ncol = 1)



offset_cols <- which(grepl("timeperiodend:sourcesim]", colnames(hbrm_post1)))

offset_draws <- hbrm_post1[,offset_cols] %>%
  mutate(rown = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rown, names_to = "site", values_to = "offset")

ggplot(filter(offset_draws, site %in% unique(offset_draws$site)[1:5]), aes(offset)) + geom_density() + facet_wrap(vars(site), ncol = 1)


```


```{r}
intercept_qis <- hbrm_post1[,intercept_cols] %>%
  median_qi() %>%
  tidyr::pivot_longer(-c(.width, .point, .interval), names_to = "var", values_to = "val") %>%
  mutate(varname = ifelse(
    grepl(".lower", var), "lower",
    ifelse(
      grepl(".upper", var), "upper",
      "median"
    )
  )) %>%
  group_by_all() %>%
  mutate(sitename = unlist(strsplit(substr(var, 13, 30), ","))[1]) %>%
  ungroup() %>%
  select(-var) %>%
  tidyr::pivot_wider(id_cols= c(sitename, .point, .width, .interval), names_from = varname, values_from = val)

ggplot(intercept_qis, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + ggtitle("Intercept")



slope_qis <- hbrm_post1[,slope_cols] %>%
  median_qi() %>%
  tidyr::pivot_longer(-c(.width, .point, .interval), names_to = "var", values_to = "val") %>%
  mutate(varname = ifelse(
    grepl(".lower", var), "lower",
    ifelse(
      grepl(".upper", var), "upper",
      "median"
    )
  )) %>%
  group_by_all() %>%
  mutate(sitename = unlist(strsplit(substr(var, 13, 30), ","))[1]) %>%
  ungroup() %>%
  select(-var) %>%
  tidyr::pivot_wider(id_cols= c(sitename, .point, .width, .interval), names_from = varname, values_from = val)

ggplot(slope_qis, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Slope")



sim_int_qis <- hbrm_post1[,sim_int_cols] %>%
  median_qi() %>%
  tidyr::pivot_longer(-c(.width, .point, .interval), names_to = "var", values_to = "val") %>%
  mutate(varname = ifelse(
    grepl(".lower", var), "lower",
    ifelse(
      grepl(".upper", var), "upper",
      "median"
    )
  )) %>%
  group_by_all() %>%
  mutate(sitename = unlist(strsplit(substr(var, 13, 30), ","))[1]) %>%
  ungroup() %>%
  select(-var) %>%
  tidyr::pivot_wider(id_cols= c(sitename, .point, .width, .interval), names_from = varname, values_from = val)

ggplot(sim_int_qis, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Sim intercept")


offset_qis <- hbrm_post1[,offset_cols] %>%
  median_qi() %>%
  tidyr::pivot_longer(-c(.width, .point, .interval), names_to = "var", values_to = "val") %>%
  mutate(varname = ifelse(
    grepl(".lower", var), "lower",
    ifelse(
      grepl(".upper", var), "upper",
      "median"
    )
  )) %>%
  group_by_all() %>%
  mutate(sitename = unlist(strsplit(substr(var, 13, 30), ","))[1]) %>%
  ungroup() %>%
  select(-var) %>%
  tidyr::pivot_wider(id_cols= c(sitename, .point, .width, .interval), names_from = varname, values_from = val)

ggplot(offset_qis, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Offset")

```

For visualization, interested in rescaling to ~comparable to the intercept for each route.

NOT FOR INFERENCE. NOT INCORPORATING VARIATION AROUND ESTIMATE FOR INTERCEPT. just ballparking it...


```{r}


rescale_val <- select(intercept_qis, sitename, median) %>% rename(rescaler = median)

slope_qis_relative <- slope_qis %>% left_join(rescale_val) %>%
  mutate(
    median = median / rescaler,
    lower = lower / rescaler,
    upper = upper / rescaler
  )
ggplot(slope_qis_relative, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Slope")


sim_int_qis_relative <- sim_int_qis %>% left_join(rescale_val) %>%
  mutate(
    median = median / rescaler,
    lower = lower / rescaler,
    upper = upper / rescaler
  )
ggplot(sim_int_qis_relative, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Sim intercept")

offset_rescale_val <- select(slope_qis, sitename, median) %>% rename(rescaler = median)


offset_qis_relative <- offset_qis %>% left_join(rescale_val) %>%
  mutate(
    median = median / rescaler,
    lower = lower / rescaler,
    upper = upper / rescaler
  )
ggplot(offset_qis_relative, aes(median, sitename)) + geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + geom_vline(xintercept = 0, color = "red")+ ggtitle("Offset relative to intercept")
offset_qis_relatives <- offset_qis %>% left_join(offset_rescale_val) %>%
  mutate(
    median = median / rescaler,
    lower = lower / rescaler,
    upper = upper / rescaler
  )
ggplot(offset_qis_relatives, aes(median, sitename)) + 
  geom_pointinterval(aes(xmin = lower, xmax = upper), size = .1) + 
  geom_point() +
  geom_vline(xintercept = 0, color = "red")+ 
  ggtitle("Offset relative to slope", subtitle=("xlims remove bars for some sites")) + 
  xlim(-10, 10)

```
