---
title: "ReSims analysis"
output: github_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(drake)
library(multipanelfigure)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake-cache-actual-resim.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")

cached(cache = cache)

loadd(all_estimates, cache = cache)

```


# working with energy use.

Estimated change due to abundance:

`estimated_sim_change_ratio` mean, upper, and lower.


```{r}

ggplot(all_estimates, aes(estimated_sim_change_ratio_mean, estimated_actual_change_ratio_mean, color= matssname)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)+
  geom_abline(intercept = 0, slope = 1) +
 # geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper, y = estimated_actual_change_ratio_mean), height = .005) +
  #geom_errorbar(aes(ymin = estimated_actual_change_ratio_lower, ymax = estimated_actual_change_ratio_upper, x = estimated_sim_change_ratio_mean), width = .005) +
  scale_color_viridis_d(option='mako', begin = .2, end =.8) +
  theme(legend.position = "none") +
  facet_wrap(vars(currency))

```

```{r}

biomass <- filter(all_estimates, currency == "biomass")

biomass_summary <- biomass %>%
  arrange(estimated_sim_change_ratio_mean) %>%
  mutate(sim_change_ratio_rank = row_number()) %>%
  mutate(omatssname = ordered(1:nrow(biomass), labels = matssname))



ggplot(biomass_summary, aes(estimated_sim_change_ratio_mean, omatssname)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper)) + 
 # geom_point(aes(x = estimated_actual_change_ratio_mean), color = "blue", alpha = .6) +
  geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), color = "blue", alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw()# +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank())

```

```{r}

loadd(all_sims, cache = cache)

ggplot(all_sims, aes(year, total_biomass, color = source)) + geom_point() + facet_wrap(vars(matssname,source), scales = "free_y")

```


Some interpretation points...

```{r}

biomass_interp <- biomass_summary %>%
  group_by_all() %>%
  mutate(
    abundance_change_ratio_over_zero = (estimated_sim_change_ratio_upper * estimated_sim_change_ratio_lower) < 0,
    currency_over_abundance = ((estimated_sim_change_ratio_upper < estimated_actual_change_ratio_lower)),
    abundance_over_currency = estimated_sim_change_ratio_lower > estimated_actual_change_ratio_upper,
    currency_decouple = currency_over_abundance | abundance_over_currency
  ) %>%
  ungroup()



ggplot(biomass_interp, aes(estimated_sim_change_ratio_mean, omatssname, color = currency_decouple)) + 
 # geom_point() +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper)) + 
 # geom_point(aes(x = estimated_actual_change_ratio_mean), color = "blue", alpha = .6) +
  geom_errorbarh(aes(xmin = estimated_actual_change_ratio_lower, xmax = estimated_actual_change_ratio_upper), alpha = .3) + 
  geom_vline(xintercept = 0) +
  theme_bw() +
  theme(axis.text.y = element_blank(), panel.grid.major= element_blank(), legend.position = "none")


ggplot(biomass_interp, aes(estimated_sim_change_ratio_mean, estimated_actual_change_ratio_mean, color= currency_decouple)) +
  geom_point() +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0)+
  geom_abline(intercept = 0, slope = 1) +
  geom_errorbarh(aes(xmin = estimated_sim_change_ratio_lower, xmax = estimated_sim_change_ratio_upper, y = estimated_actual_change_ratio_mean), height = .005) +
  geom_errorbar(aes(ymin = estimated_actual_change_ratio_lower, ymax = estimated_actual_change_ratio_upper, x = estimated_sim_change_ratio_mean), width = .005) +
  scale_color_viridis_d(option='mako', begin = .2, end =.8) +
  theme_bw() +
  theme(legend.position = "bottom")


mean(biomass_interp$abundance_change_ratio_over_zero)
mean(biomass_interp$estimated_sim_change_ratio_lower > 0)
mean(biomass_interp$estimated_sim_change_ratio_upper < 0)

mean(biomass_interp$abundance_over_currency)
mean(biomass_interp$currency_over_abundance)
mean(biomass_interp$currency_decouple)




```


